[env:esp32doit-devkit-v1]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    mikalhart/TinyGPSPlus @ ^1.0.3

board_build.partitions = partitions.csv

build_flags =
    -DCORE_DEBUG_LEVEL=0
